name: Build Android Release APK

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: üèó Setup Repo
        uses: actions/checkout@v4

      - name: üèó Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: üèó Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: üì¶ Install Dependencies
        run: npm ci

      - name: ‚öôÔ∏è Expo Prebuild
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          EXPO_PUBLIC_TMDB_API_KEY: ${{ secrets.EXPO_PUBLIC_TMDB_API_KEY }}
          EXPO_PUBLIC_TRAKT_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_TRAKT_CLIENT_ID }}
          EXPO_PUBLIC_TRAKT_CLIENT_SECRET: ${{ secrets.EXPO_PUBLIC_TRAKT_CLIENT_SECRET }}
        run: npx expo prebuild --platform android --no-install


      - name: üèó Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.1.0
          cache-read-only: false

      - name: ‚òïÔ∏è Build Android Release APK
        working-directory: ./android
        env:
          GRADLE_OPTS: "-Xmx3584m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=\"-Xmx3584m -XX:MaxMetaspaceSize=512m\""
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          EXPO_PUBLIC_TMDB_API_KEY: ${{ secrets.EXPO_PUBLIC_TMDB_API_KEY }}
          EXPO_PUBLIC_TRAKT_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_TRAKT_CLIENT_ID }}
          EXPO_PUBLIC_TRAKT_CLIENT_SECRET: ${{ secrets.EXPO_PUBLIC_TRAKT_CLIENT_SECRET }}
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease \
            --parallel \
            --build-cache

      - name: üì§ Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: crispy-native-release-apk
          path: android/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
          retention-days: 7
